version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - django-network

volumes:
  postgres_data:
  redis_data:

networks:
  django-network:
